terminate called after throwing an instance of 'std::runtime_error'
  what():  generic_type: cannot initialize type "WorkerId": an object with that name is already defined
/var/spool/slurmd/job1029775/slurm_script: line 19: 30508 Aborted                 python3 sequential_inference.py 5000 1000 64 all_weights_what
